# Generated by Django 5.2 on 2025-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=35, null=True)),
                ('categoryimage', models.ImageField(null=True, upload_to='media')),
                ('categorystatus', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
