# Generated by Django 5.2 on 2025-05-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategoryname', models.CharField(max_length=30, null=True)),
                ('SubCategoryimage', models.ImageField(null=True, upload_to='media')),
                ('SubCategorystatus', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
