# Generated by Django 5.2 on 2025-05-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0002_tbl_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_subcategory',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_category'),
            preserve_default=False,
        ),
    ]
