# Generated by Django 5.2 on 2025-05-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0003_tbl_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=45, null=True)),
                ('Productimage', models.ImageField(null=True, upload_to='media')),
                ('productstatus', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
