# Generated by Django 5.2 on 2025-05-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0004_tbl_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_products',
            old_name='productstatus',
            new_name='Productprice',
        ),
        migrations.AddField(
            model_name='tbl_products',
            name='Productdescription',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tbl_products',
            name='Productoffer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tbl_products',
            name='Productweight',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
