# Generated by Django 5.2 on 2025-05-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0005_rename_productstatus_tbl_products_productprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_products',
            name='Productofferprice',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
