# Generated by Django 5.2 on 2025-05-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0006_tbl_products_productofferprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_products',
            old_name='Productoffer',
            new_name='ProductNumofpieces',
        ),
        migrations.AddField(
            model_name='tbl_products',
            name='ProductStockin',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tbl_products',
            name='ProductStockout',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
