# Generated by Django 5.2 on 2025-05-22 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0007_rename_productoffer_tbl_products_productnumofpieces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_products',
            name='SubCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_subcategory'),
        ),
        migrations.AddField(
            model_name='tbl_products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_category'),
        ),
    ]
