# Generated by Django 5.2 on 2025-06-17 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0008_tbl_products_subcategory_tbl_products_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=40, null=True)),
                ('Mobile', models.IntegerField(null=True)),
                ('Email', models.CharField(max_length=40, null=True)),
                ('Password', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('session_key', models.CharField(max_length=40, null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_products')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_signup')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_products')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_signup')),
            ],
        ),
    ]
