# Generated by Django 5.2 on 2025-06-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0009_tbl_signup_tbl_cart_tbl_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_products',
            name='Productofferprice',
            field=models.IntegerField(null=True),
        ),
    ]
