# Generated by Django 5.2 on 2025-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0010_alter_tbl_products_productofferprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_signup',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='tbl_signup',
            name='Fullname',
        ),
        migrations.AddField(
            model_name='tbl_signup',
            name='Username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_signup',
            name='Password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
