# Generated by Django 5.2 on 2025-06-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0011_remove_tbl_signup_email_remove_tbl_signup_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=40, null=True)),
                ('Address', models.CharField(max_length=300, null=True)),
                ('Phonenumber', models.IntegerField(null=True)),
                ('Paymentmethod', models.CharField(max_length=50, null=True)),
                ('Total_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(null=True)),
                ('session_key', models.CharField(max_length=40, null=True)),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_products')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_signup')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_order')),
            ],
        ),
    ]
