# Generated by Django 5.2 on 2025-06-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0012_tbl_order_tbl_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order',
            name='Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=40),
        ),
    ]
