# Generated by Django 5.2 on 2025-07-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0013_tbl_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Delivery_partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Contact', models.IntegerField(null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=300, null=True)),
                ('Vehicledetails', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
