# Generated by Django 5.2 on 2025-07-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0014_tbl_delivery_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order',
            name='DeliveryPartner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Grocerapp.tbl_delivery_partners'),
        ),
    ]
