# Generated by Django 5.2 on 2025-07-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0015_tbl_order_deliverypartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_order_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryboyid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_delivery_partners')),
                ('orderid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_order')),
            ],
        ),
    ]
