# Generated by Django 5.2 on 2025-07-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0016_tbl_order_assign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_order_assign',
            old_name='orderid',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='tbl_order_assign',
            old_name='deliveryboyid',
            new_name='partner_id',
        ),
        migrations.RemoveField(
            model_name='tbl_order',
            name='DeliveryPartner',
        ),
        migrations.AddField(
            model_name='tbl_order_assign',
            name='createdtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
