# Generated by Django 5.2 on 2025-07-18 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0017_rename_orderid_tbl_order_assign_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_order_assign',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Delivery_order', to='Grocerapp.tbl_order'),
        ),
        migrations.AlterField(
            model_name='tbl_order_assign',
            name='partner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Delivery', to='Grocerapp.tbl_delivery_partners'),
        ),
    ]
