# Generated by Django 5.2 on 2025-07-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0018_alter_tbl_order_assign_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_delivery_partners',
            name='Email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_delivery_partners',
            name='Password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
