# Generated by Django 5.2 on 2025-09-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0019_tbl_delivery_partners_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_contact_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
