# Generated by Django 5.2 on 2025-11-03 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocerapp', '0020_tbl_contact_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Grocerapp.tbl_signup'),
        ),
    ]
